# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.6'
  displayName: 'Install Node.js'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'demo'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'sqa_b8234bbd0c0e5ad47f42425b8ccc947f44e6b871'
    cliProjectName: 'sqa_b8234bbd0c0e5ad47f42425b8ccc947f44e6b871'
    cliSources: '.'
- script: |
    npm install -g react-cli react
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: '$(Build.SourcesDirectory)'
- task: SonarQubeAnalyze@5
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'