trigger:

- master



pool:

  name: default



steps:

- task: NodeTool@0

  inputs:

    versionSpec: '14.17.6'

  displayName: 'Install Node.js'



- script: |

    npm install -g react-cli react

    npm install

    npm run build

  displayName: "npm install and build"

  workingDirectory: '$(Build.SourcesDirectory)'



- task: ArchiveFiles@2

  inputs:

    rootFolderOrFile: '$(Build.SourcesDirectory)/build'

    includeRootFolder: true

    archiveType: 'zip'

    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

    replaceExistingArchive: true